CXX = g++
CXXFLAGS = -Wall -O0 -Wextra -pedantic
LINKPATH = -I./samtools-0.1.19 -L./samtools-0.1.19
LINKFLAGS = -lbam -lz -lm -lpthread
DEBUGFLAGS = -ggdb3 -fsanitize=address,undefined

all: junc

junc: junc.o
	$(CXX) -o $@ $(LINKPATH) $(CXXFLAGS) $(DEBUGFLAGS) junc.o $(LINKFLAGS)

junc.o: FindJunction.cpp
	$(CXX) -c -o $@ $(LINKPATH) $(CXXFLAGS) $(DEBUGFLAGS) $< $(LINKFLAGS)
